# Fail2Ban configuration file
#
# Regexp to catch specific URL patterns


[Definition]

failregex = ^<HOST> -.*(Custom-Async|Go-http|Firefox/..\.|Chrome...\.|MSIE|cgi-bin|/HNAP1|\.getodin\.|\.git/|eval-stdin|l9explore|Infrawatch/|wp-admin|wp-filemanager|ce.sys.io/|getodin.com/|developer.amazon.com) 

ignoreregex =

datepattern = ^[^\[]*\[({DATE})
              {^LN-BEG}

# Author: Pierre HENAUT
