# Fail2Ban configuration file
#
# Regexp to catch known spambots and software alike. Please verify
# that it is your intent to block IPs which were driven by
# above mentioned bots.


[Definition]

failregex = ^<HOST> -.*(
        Custom-Async|
        Go-http|
        Firefox/..\.|
        Chrome...\.|
        MSIE|
        cgi-bin|
        /HNAP1|
        \.getodin\.|
        \.git/|
        eval-stdin|
        l9explore|
        Infrawatch/|
        wp-admin|
        wp-filemanager|
        ce.sys.io/|
        getodin.com/|
        developer.amazon.com
        ) 

ignoreregex =

datepattern = ^[^\[]*\[({DATE})
              {^LN-BEG}

# DEV Notes:
# List of bad bots fetched from http://www.user-agents.org
# Generated on Thu Nov  7 14:23:35 PST 2013 by files/gen_badbots.
#
# Author: Pierre HENAUT
