[DEFAULT]
banaction = nftables
banaction_allports = nftables[type=allports]
backend = systemd
ignoreip = 127.0.0.1 192.168.1.171
findtime = 60m
bantime = 24h
maxretry = 1

[sshd]
enabled = false

[apache-auth]
enabled = true
logpath = /var/snap/nextcloud/current/logs/apache_access.log

[apache-badbots]
enabled = true
logpath = /var/snap/nextcloud/current/logs/apache_access.log

[apache-noscript]
enabled = true
logpath = /var/snap/nextcloud/current/logs/apache_access.log

[apache-overflows]
enabled = true
logpath = /var/snap/nextcloud/current/logs/apache_access.log

[apache-nohome]
enabled = true
logpath = /var/snap/nextcloud/current/logs/apache_access.log

[apache-botsearch]
enabled = true
logpath = /var/snap/nextcloud/current/logs/apache_access.log

[apache-fakegooglebot]
enabled = true
logpath = /var/snap/nextcloud/current/logs/apache_access.log

[apache-modsecurity]
enabled = true
logpath = /var/snap/nextcloud/current/logs/apache_access.log

[apache-shellshock]
enabled = true
logpath = /var/snap/nextcloud/current/logs/apache_access.log

[apache-phe]
enabled = true
backend = auto
logpath = /var/snap/nextcloud/current/logs/apache_access.log
